# Generated by Django 4.1 on 2024-05-22 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0003_rename_caritems_cartitems_addresses'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='addresses',
            unique_together={('zip_code', 'prefecture', 'address')},
        ),
    ]
